import type { NLMSong } from '../../../services/api';

export type DemoTrack = NLMSong;

const now = '2026-09-30T00:00:00.000Z';

const sampleAudio = 'https://assets.mixkit.co/active_storage/sfx/256/256-preview.mp3';
const sampleAudioTwo = 'https://assets.mixkit.co/active_storage/sfx/257/257-preview.mp3';
const sampleAudioThree = 'https://assets.mixkit.co/active_storage/sfx/258/258-preview.mp3';

export const DEMO_NLM_CATALOG: DemoTrack[] = [
  {
    id: 'demo-electric-dusk',
    title: 'Electric Dusk',
    artist: 'NLM Studio',
    description: 'A synthwave journey through neon-soaked cityscapes, where every bassline pulses like a heartbeat.',
    genre: 'Synthwave',
    tags: ['retro', 'electronic', 'nightdrive'],
    lyrics: '[00:10] Neon reflections on wet streets tonight\n[00:22] Racing against the dawn, I feel alive\n[00:34] Electric whispers in the midnight air\n[00:46] Every shadow is a story we share',
    audioUrl: sampleAudio,
    thumbnailUrl: null,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-midnight-echoes',
    title: 'Midnight Echoes',
    artist: 'NLM Studio',
    description: 'Ambient textures and field recordings weave a sonic landscape for late-night reflection.',
    genre: 'Ambient',
    tags: ['chill', 'atmospheric', 'focus'],
    lyrics: '[00:00] Silence speaks in echoes of the past\n[00:30] Midnight calls, the stars will fade\n[00:58] Time moves slow when you are lost in thought\n[01:26] Echoes linger long after you\'ve gone',
    audioUrl: sampleAudioTwo,
    thumbnailUrl: null,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-river-run',
    title: 'River Run',
    artist: 'NLM Studio',
    description: 'An upbeat fusion of acoustic guitar and electronic drums, carrying the flow of a restless spirit.',
    genre: 'Indie Pop',
    tags: ['upbeat', 'acoustic', 'morning'],
    lyrics: '[00:12] Gotta keep moving, river run my way\n[00:24] Gotta keep moving, river run my way\n[00:36] Gotta keep moving, river run my way\n[00:48] Gotta keep moving, river run my way',
    audioUrl: sampleAudioThree,
    thumbnailUrl: null,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-cobalt-dreams',
    title: 'Cobalt Dreams',
    artist: 'NLM Studio',
    description: 'Deep bass and glitchy percussion create an immersive electronic soundscape.',
    genre: 'Electronic',
    tags: ['deep', 'bass', 'glitch'],
    lyrics: '[00:05] Cobalt dreams in a digital haze\n[00:20] Reality bends and rearranges\n[00:35] Pulses of light through static clear\n[00:50] Wake me before the dawn draws near',
    audioUrl: sampleAudio,
    thumbnailUrl: null,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-velvet-horizon',
    title: 'Velvet Horizon',
    artist: 'NLM Studio',
    description: 'Smooth jazz chords blend with subtle electronic flourishes for a sophisticated listening experience.',
    genre: 'Jazz',
    tags: ['smooth', 'sophisticated', 'late night'],
    lyrics: '[00:00] Velvet horizon, painting skies\n[00:30] Every promise, every lie\n[00:58] Softly spoken, barely heard\n[01:26] Velvet words inside my head',
    audioUrl: sampleAudioTwo,
    thumbnailUrl: null,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-ghost-notes',
    title: 'Ghost Notes',
    artist: 'NLM Studio',
    description: 'Hip-hop infused with live instrumentation and soulful vocal samples.',
    genre: 'Hip-Hop',
    tags: ['live', 'soul', 'boom-bap'],
    lyrics: '[00:15] Ghost notes in the silence scream\n[00:28] Broken dreams and broken seams\n[00:40] I wrote my truth in invisible ink\n[00:52] On the walls of everything',
    audioUrl: sampleAudioThree,
    thumbnailUrl: null,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-solar-flare',
    title: 'Solar Flare',
    artist: 'NLM Studio',
    description: 'High-energy track driven by punchy 808s and anthemic synth leads.',
    genre: 'Trap',
    tags: ['hard', '808s', 'anthem'],
    lyrics: '[00:10] Solar flare, burning up my mind\n[00:20] Can\'t slow down, gotta leave it behind\n[00:30] Solar flare, light up the night\n[00:40] Gonna make it glow until the morning light',
    audioUrl: sampleAudio,
    thumbnailUrl: null,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-crystal-memory',
    title: 'Crystal Memory',
    artist: 'NLM Studio',
    description: 'Ethereal vocals float over ambient pads and gentle arpeggios.',
    genre: 'Downtempo',
    tags: ['ethereal', 'dreamy', 'study'],
    lyrics: '[00:00] Crystal memory, fragile as a dream\n[00:30] Every moment fades into the stream\n[00:58] Hold me close, don\'t let me fall\n[01:26] Through the silence, I hear it all',
    audioUrl: sampleAudioTwo,
    thumbnailUrl: null,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-neon-river',
    title: 'Neon River',
    artist: 'NLM Studio',
    description: 'Driving rhythms and catchy hooks make this a dancefloor-ready track.',
    genre: 'Pop',
    tags: ['catchy', 'dance', 'radio'],
    lyrics: '[00:12] Let the neon river carry you\n[00:24] Let the neon river carry you\n[00:36] Down the street where the lights all glow\n[00:48] Let the neon river carry you',
    audioUrl: sampleAudioThree,
    thumbnailUrl: null,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-static-horizon',
    title: 'Static Horizon',
    artist: 'NLM Studio',
    description: 'Minimalist electronic with glitch elements and subtle harmonic progressions.',
    genre: 'IDM',
    tags: ['minimal', 'glitch', 'focus'],
    lyrics: '',
    audioUrl: sampleAudio,
    thumbnailUrl: null,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const getDemoTrack = (id?: string) => DEMO_NLM_CATALOG.find((track) => track.id === id) ?? null;

export const DEMO_GENRES = [
  { label: 'Electronic', query: 'Electronic', color: '--nlm-coral' },
  { label: 'Ambient', query: 'Ambient', color: '--nlm-lime' },
  { label: 'Synthwave', query: 'Synthwave', color: '--nlm-coral' },
  { label: 'Hip-Hop', query: 'Hip-Hop', color: '--nlm-lime' },
  { label: 'Jazz', query: 'Jazz', color: '--nlm-coral' },
  { label: 'Indie Pop', query: 'Indie Pop', color: '--nlm-lime' },
  { label: 'Trap', query: 'Trap', color: '--nlm-coral' },
  { label: 'Downtempo', query: 'Downtempo', color: '--nlm-lime' },
  { label: 'IDM', query: 'IDM', color: '--nlm-coral' },
  { label: 'Pop', query: 'Pop', color: '--nlm-lime' },
];
